### ISSUE TITLE
Checkout process - Payment method

### ISSUE THREAD

**Issue by drtikol** [smartstoreag/SmartStoreNET#1056]
Once when select payment method and then go back to shipping method, i cannot chanage payment.
The IsPaymentSelectionSkipped on state is always setting to true

**Comment by Michael-Herzog** [comment]
Cannot be reproduced. For button checkout payment methods customers decide for the payment methods (and thus for different checkout flows) on the cart page and have to go back there to decide for another checkout process else they're stuck in their chosen checkout flow which is totally correct, because with other checkout flows addresses etc. have to entered in a different way.
