### ISSUE TITLE
Currency selector OffCanvas - doesn't let you select/change currency

### ISSUE THREAD

**Issue by SilverSearcher** [smartstoreag/SmartStoreNET#1158]

**Comment by Michael-Herzog** [comment]
On hhich device or browser have you seen this? 
I can repoduce it only with IE11.

**Comment by SilverSearcher** [comment]
Hi - 

Multiple Android, I've not had a chance to test iOS. I've not seen (noticed) any issues on Desktop browsers - only mobile.

Samsung S7 smartphone running 7.0 Nougat
Samsung Tab running Ice Cream Sandwich
Sprint PCS Tab running Lollipop

I've tried Firefox (my default on all) and the other Android device/browsers defaults.

Works fine on a desktop in emulation mode e.g. desktop with Firefox using devtoolbar in mobile mode.

**Comment by SalehGladius** [comment]
In Google Chrome, when resize window to moblie frame size, currency and language selector don't work!

**Comment by Michael-Herzog** [comment]
Hi,

I don't know why it worked the first time I've tested it but now I can reproduce the problem and will fix it asap. I've already found out that the problem is caused by select2 skining. So a workaround would be to alter the script:
src\presentation\smartstore.web\themes\flex\scripts\public.offcanvas-menu.js

Just comment out line 362 applyCommonPlugins(footer);

Regards
