### ISSUE TITLE
How to theme a widget plugin

### ISSUE THREAD

**Issue by ste2425** [smartstoreag/SmartStoreNET#665]
Hi, hoping someone can explain how to accomplish the above task.

My plugin is injected onto the page using @Html.widget(""). I initially took the same approach as you do for themeing core pages, took the folder out the plugins view folder and placed that inside the themes view folder. However this isn't the case. 

I can't seem to find any examples of this being implemented in SmartStore itself. I get the feeling its some sort of naming convention. Thanks for your time.

**Comment by muratcakir** [comment]
Please use our [support forums](http://community.smartstore.com/) for this kind of **question** in future.

But anyway, theming within plugins is not supported at this moment (and will probably never be). That means: you cannot create subfolders for themes in your plugin's view folder. This is by design: plugin templates should be designed theme-agnostic and should always look ok, regardless of the chosen theme.
