### ISSUE TITLE
ASP.NET Core (vNext)

### ISSUE THREAD

**Issue by rcince** [smartstoreag/SmartStoreNET#926]
Not and issue. Are there any intentions to make this .Net core compatible ?

**Comment by MichaelCsitkovics** [comment]
Nice idea, but definitely an immense effort. EF7, MVC6 and all dependencies...

**Comment by muratcakir** [comment]
A migration to ASP.NET 5 Core + MVC 6 is definitely on our roadmap, but this will take a while. Many parts of SmartStore.NET must be developed from scratch in order to benefit from platform independence. Without dnxcore an upgrade does not make any sense, it would just be an upgrade with no real user benefit, except for slightly better performance.
 
Furthermore, dnxcore will not be mature enough with it's initial release to fulfill all requirements of complex frameworks like SmartStore.NET:
- No real concept for modular applications with pluggable components
- No built-in email sending (!)
- No lazy loading with Entity Framework 7
- Lack of MVC child actions (the new alternative ViewComponents are a piece of shit... no model binding etc.)

So we have to wait for a more mature release or for 3rd parties to fill the gaps.
